CREATE TABLE [dbo].[SalesP]
(
[RECNUM] [int] NOT NULL IDENTITY(1, 1),
[ID] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SalesP__ID__5165187F] DEFAULT (''),
[Name] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SalesP__Name__52593CB8] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SalesP] ADD CONSTRAINT [SalesP001_PK] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [SalesP002] ON [dbo].[SalesP] ([Name], [ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [SalesP000] ON [dbo].[SalesP] ([RECNUM]) ON [PRIMARY]
GO
