CREATE TABLE [dbo].[CodeMast]
(
[RECNUM] [int] NOT NULL IDENTITY(1, 1),
[Type] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__CodeMast__Type__6FE99F9F] DEFAULT (''),
[Code] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__CodeMast__Code__70DDC3D8] DEFAULT (''),
[Description] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__CodeMast__Descri__71D1E811] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CodeMast] ADD CONSTRAINT [CodeMast001_PK] PRIMARY KEY CLUSTERED  ([Type], [Code]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [CodeMast000] ON [dbo].[CodeMast] ([RECNUM]) ON [PRIMARY]
GO
