CREATE TABLE [dbo].[Vendor]
(
[RECNUM] [int] NOT NULL IDENTITY(1, 1),
[ID] [int] NOT NULL CONSTRAINT [DF__Vendor__ID__2E1BDC42] DEFAULT ((0)),
[Name] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Vendor__Name__2F10007B] DEFAULT (''),
[Address] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Vendor__Address__300424B4] DEFAULT (''),
[City] [char] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Vendor__City__30F848ED] DEFAULT (''),
[State] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Vendor__State__31EC6D26] DEFAULT (''),
[Zip] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Vendor__Zip__32E0915F] DEFAULT (''),
[Phone_Number] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Vendor__Phone_Nu__33D4B598] DEFAULT (''),
[Fax_Number] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Vendor__Fax_Numb__34C8D9D1] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Vendor] ADD CONSTRAINT [Vendor001_PK] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Vendor002] ON [dbo].[Vendor] ([Name], [ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Vendor000] ON [dbo].[Vendor] ([RECNUM]) ON [PRIMARY]
GO
